### ISSUE TITLE
I think that C++ and Java must be included

### ISSUE THREAD

**Issue by pacastillo** [geneura-papers/2015-ea-languages#3]
or at least, indicate that the paper focuses on interpreted languages.

**Comment by JJ** [comment]
So many languages could be included... if you want to do C++ ;-)

2015-11-02 21:02 GMT+01:00 Pedro A. Castillo Valdivieso <
notifications@github.com>:

> or at least, indicate that the paper focuses on interpreted languages.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-ea-languages/issues/3.

## 

JJ

**Comment by pacastillo** [comment]
I can try. Maybe as a baseline for the comparison.

What are the operations being compared? Where is the source code in JS?

**Comment by JJ** [comment]
It's only mutation. Click to the file on the paper, and go to the rest of
the package to see where mutation has been implemented.

2015-11-02 22:23 GMT+01:00 Pedro A. Castillo Valdivieso <
notifications@github.com>:

> I can try. Maybe as a baseline for the comparison.
> 
> What are the operations being compared? Where is the source code in JS?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-ea-languages/issues/3#issuecomment-153161331
> .

## 

JJ

**Comment by pacastillo** [comment]
The results using C++ are as follows in an AMD Phenom(tm) 9950 Quad-Core Processor  2600 MHz:

Run 1
C++, BitString, 16, 0.422403
C++, BitString, 32, 0.426266
C++, BitString, 64, 0.425221
C++, BitString, 128, 0.41582
C++, BitString, 256, 0.415288
C++, BitString, 512, 0.415195
C++, BitString, 1024, 0.425319
C++, BitString, 2048, 0.463571
C++, BitString, 4096, 0.426933
C++, BitString, 8192, 0.442776
C++, BitString, 16384, 0.545644
C++, BitString, 32768, 0.470763
Run 2
C++, BitString, 16, 0.42545
C++, BitString, 32, 0.424554
C++, BitString, 64, 0.425207
C++, BitString, 128, 0.425253
C++, BitString, 256, 0.43281
C++, BitString, 512, 0.425186
C++, BitString, 1024, 0.503575
C++, BitString, 2048, 0.524728
C++, BitString, 4096, 0.433815
C++, BitString, 8192, 0.461325
C++, BitString, 16384, 0.442974
C++, BitString, 32768, 0.41784
Run 3
C++, BitString, 16, 0.433699
C++, BitString, 32, 0.41818
C++, BitString, 64, 0.417731
C++, BitString, 128, 0.423826
C++, BitString, 256, 0.417037
C++, BitString, 512, 0.414883
C++, BitString, 1024, 0.414045
C++, BitString, 2048, 0.415637
C++, BitString, 4096, 0.415397
C++, BitString, 8192, 0.439671
C++, BitString, 16384, 0.414533
C++, BitString, 32768, 0.414182
Run 4
C++, BitString, 16, 0.427966
C++, BitString, 32, 0.417014
C++, BitString, 64, 0.427606
C++, BitString, 128, 0.418395
C++, BitString, 256, 0.415571
C++, BitString, 512, 0.42391
C++, BitString, 1024, 0.414643
C++, BitString, 2048, 0.415433
C++, BitString, 4096, 0.41561
C++, BitString, 8192, 0.448822
C++, BitString, 16384, 0.414323
C++, BitString, 32768, 0.413535
Run 5
C++, BitString, 16, 0.431356
C++, BitString, 32, 0.422213
C++, BitString, 64, 0.453095
C++, BitString, 128, 0.442767
C++, BitString, 256, 0.416202
C++, BitString, 512, 0.416497
C++, BitString, 1024, 0.415827
C++, BitString, 2048, 0.533891
C++, BitString, 4096, 0.485458
C++, BitString, 8192, 0.467747
C++, BitString, 16384, 0.436501
C++, BitString, 32768, 0.433313
Run 6
C++, BitString, 16, 0.43462
C++, BitString, 32, 0.43068
C++, BitString, 64, 0.446834
C++, BitString, 128, 0.472723
C++, BitString, 256, 0.583846
C++, BitString, 512, 0.474598
C++, BitString, 1024, 0.464281
C++, BitString, 2048, 0.460874
C++, BitString, 4096, 0.443425
C++, BitString, 8192, 0.488871
C++, BitString, 16384, 0.4848
C++, BitString, 32768, 0.49677
Run 7
C++, BitString, 16, 0.420075
C++, BitString, 32, 0.425139
C++, BitString, 64, 0.417339
C++, BitString, 128, 0.419743
C++, BitString, 256, 0.451052
C++, BitString, 512, 0.41646
C++, BitString, 1024, 0.416267
C++, BitString, 2048, 0.415423
C++, BitString, 4096, 0.417387
C++, BitString, 8192, 0.416089
C++, BitString, 16384, 0.420611
C++, BitString, 32768, 0.415052
Run 8
C++, BitString, 16, 0.424497
C++, BitString, 32, 0.431792
C++, BitString, 64, 0.417478
C++, BitString, 128, 0.420452
C++, BitString, 256, 0.438455
C++, BitString, 512, 0.420922
C++, BitString, 1024, 0.436456
C++, BitString, 2048, 0.429361
C++, BitString, 4096, 0.415332
C++, BitString, 8192, 0.425735
C++, BitString, 16384, 0.417436
C++, BitString, 32768, 0.415156
Run 9
C++, BitString, 16, 0.439319
C++, BitString, 32, 0.425214
C++, BitString, 64, 0.424764
C++, BitString, 128, 0.414197
C++, BitString, 256, 0.415287
C++, BitString, 512, 0.415188
C++, BitString, 1024, 0.448265
C++, BitString, 2048, 0.414959
C++, BitString, 4096, 0.415156
C++, BitString, 8192, 0.424753
C++, BitString, 16384, 0.415578
C++, BitString, 32768, 0.414262

I have used the (very) old EO library   ;)
I send the source code via email.

**Comment by pacastillo** [comment]
Well, I have make available the "bfcpp" C++ source code at:
       https://github.com/pacastillo/eo_revival

;)

**Comment by JJ** [comment]
Great!

2015-11-04 0:38 GMT+01:00 Pedro A. Castillo Valdivieso <
notifications@github.com>:

> Well, I have make available the "bfcpp" C++ source code at:
> https://github.com/pacastillo/eo_revival
> 
> ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-ea-languages/issues/3#issuecomment-153524841
> .

## 

JJ

**Comment by gstvrmrlpz** [comment]
He añadido un código de ejemplo en c++ al repositorio.
Lo digo porque creo que sería bueno que todos los ejemplos se ejecutasen en la misma máquina...

**Comment by deantares** [comment]
A java version joined to the figth!

java-bitflip:16 , 0.011991155
java-bitflip:32 , 0.001751324
java-bitflip:64 , 0.00162794
java-bitflip:128 , 0.001614214
java-bitflip:256 , 0.001603337
java-bitflip:512 , 0.001589423
java-bitflip:1024 , 0.001250517
java-bitflip:2048 , 0.001266544
java-bitflip:4096 , 0.001208259
java-bitflip:8192 , 0.001114301
java-bitflip:16384 , 0.001111242
java-bitflip:32768 , 0.001671325

java-bitflip:16 , 0.008113708
java-bitflip:32 , 0.001617772
java-bitflip:64 , 0.001625787
java-bitflip:128 , 0.002042154
java-bitflip:256 , 0.002229686
java-bitflip:512 , 0.001619736
java-bitflip:1024 , 0.001330667
java-bitflip:2048 , 0.001303118
java-bitflip:4096 , 0.001287164
java-bitflip:8192 , 0.001329467
java-bitflip:16384 , 0.001161452
java-bitflip:32768 , 0.001100067

java-bitflip:16 , 0.007946466
java-bitflip:32 , 0.003087392
java-bitflip:64 , 0.001624249
java-bitflip:128 , 0.001632813
java-bitflip:256 , 0.00165737
java-bitflip:512 , 0.001645393
java-bitflip:1024 , 0.001373129
java-bitflip:2048 , 0.001235582
java-bitflip:4096 , 0.00121639
java-bitflip:8192 , 0.001121656
java-bitflip:16384 , 0.001188214
java-bitflip:32768 , 0.001120767

java-bitflip:16 , 0.009791494
java-bitflip:32 , 0.001629245
java-bitflip:64 , 0.001603784
java-bitflip:128 , 0.001615841
java-bitflip:256 , 0.001627643
java-bitflip:512 , 0.001611503
java-bitflip:1024 , 0.001306669
java-bitflip:2048 , 0.001244566
java-bitflip:4096 , 0.001293915
java-bitflip:8192 , 0.001149508
java-bitflip:16384 , 0.001102308
java-bitflip:32768 , 0.001116782

java-bitflip:16 , 0.008489137
java-bitflip:32 , 0.002592102
java-bitflip:64 , 0.002714038
java-bitflip:128 , 0.002660729
java-bitflip:256 , 0.002731328
java-bitflip:512 , 0.001386984
java-bitflip:1024 , 0.001290418
java-bitflip:2048 , 0.001144125
java-bitflip:4096 , 0.001292783
java-bitflip:8192 , 0.001423453
java-bitflip:16384 , 0.001433209
java-bitflip:32768 , 0.001503469

java-bitflip:16 , 0.009666127
java-bitflip:32 , 0.002560116
java-bitflip:64 , 0.002220535
java-bitflip:128 , 0.001608121
java-bitflip:256 , 0.001234845
java-bitflip:512 , 0.002430928
java-bitflip:1024 , 0.001766015
java-bitflip:2048 , 0.001581484
java-bitflip:4096 , 0.001593586
java-bitflip:8192 , 0.001952664
java-bitflip:16384 , 0.001619234
java-bitflip:32768 , 0.001135541

java-bitflip:16 , 0.011118166
java-bitflip:32 , 0.002650564
java-bitflip:64 , 0.00263125
java-bitflip:128 , 0.002709398
java-bitflip:256 , 0.002779049
java-bitflip:512 , 0.001977314
java-bitflip:1024 , 0.001177237
java-bitflip:2048 , 0.001140026
java-bitflip:4096 , 0.001119551
java-bitflip:8192 , 0.001119437
java-bitflip:16384 , 0.001133325
java-bitflip:32768 , 0.001180998

java-bitflip:16 , 0.008716385
java-bitflip:32 , 0.002544727
java-bitflip:64 , 0.002694378
java-bitflip:128 , 0.00263498
java-bitflip:256 , 0.002738082
java-bitflip:512 , 0.002182567
java-bitflip:1024 , 0.001165694
java-bitflip:2048 , 0.001139437
java-bitflip:4096 , 0.001103763
java-bitflip:8192 , 0.001098939
java-bitflip:16384 , 0.00108477
java-bitflip:32768 , 0.001105667

java-bitflip:16 , 0.007868587
java-bitflip:32 , 0.003056887
java-bitflip:64 , 0.001623479
java-bitflip:128 , 0.001607546
java-bitflip:256 , 0.001639512
java-bitflip:512 , 0.001386188
java-bitflip:1024 , 0.001190691
java-bitflip:2048 , 0.001182292
java-bitflip:4096 , 0.001160852
java-bitflip:8192 , 0.001216561
java-bitflip:16384 , 0.001332583
java-bitflip:32768 , 0.001317823

java-bitflip:16 , 0.008350494
java-bitflip:32 , 0.001658587
java-bitflip:64 , 0.001612241
java-bitflip:128 , 0.001631172
java-bitflip:256 , 0.001599996
java-bitflip:512 , 0.00197649
java-bitflip:1024 , 0.001307362
java-bitflip:2048 , 0.001154928
java-bitflip:4096 , 0.001319034
java-bitflip:8192 , 0.001147935
java-bitflip:16384 , 0.00115144
java-bitflip:32768 , 0.001104784

**Comment by JJ** [comment]
Great! It's double blind now, but add your name as a comment to the paper!

2015-11-05 14:39 GMT+01:00 Antonio Fernández Ares notifications@github.com
:

> A java version joined to the figth!
> 
> java-bitflip:16 , 0.011991155
> java-bitflip:32 , 0.001751324
> java-bitflip:64 , 0.00162794
> java-bitflip:128 , 0.001614214
> java-bitflip:256 , 0.001603337
> java-bitflip:512 , 0.001589423
> java-bitflip:1024 , 0.001250517
> java-bitflip:2048 , 0.001266544
> java-bitflip:4096 , 0.001208259
> java-bitflip:8192 , 0.001114301
> java-bitflip:16384 , 0.001111242
> java-bitflip:32768 , 0.001671325
> 
> java-bitflip:16 , 0.008113708
> java-bitflip:32 , 0.001617772
> java-bitflip:64 , 0.001625787
> java-bitflip:128 , 0.002042154
> java-bitflip:256 , 0.002229686
> java-bitflip:512 , 0.001619736
> java-bitflip:1024 , 0.001330667
> java-bitflip:2048 , 0.001303118
> java-bitflip:4096 , 0.001287164
> java-bitflip:8192 , 0.001329467
> java-bitflip:16384 , 0.001161452
> java-bitflip:32768 , 0.001100067
> 
> java-bitflip:16 , 0.007946466
> java-bitflip:32 , 0.003087392
> java-bitflip:64 , 0.001624249
> java-bitflip:128 , 0.001632813
> java-bitflip:256 , 0.00165737
> java-bitflip:512 , 0.001645393
> java-bitflip:1024 , 0.001373129
> java-bitflip:2048 , 0.001235582
> java-bitflip:4096 , 0.00121639
> java-bitflip:8192 , 0.001121656
> java-bitflip:16384 , 0.001188214
> java-bitflip:32768 , 0.001120767
> 
> java-bitflip:16 , 0.009791494
> java-bitflip:32 , 0.001629245
> java-bitflip:64 , 0.001603784
> java-bitflip:128 , 0.001615841
> java-bitflip:256 , 0.001627643
> java-bitflip:512 , 0.001611503
> java-bitflip:1024 , 0.001306669
> java-bitflip:2048 , 0.001244566
> java-bitflip:4096 , 0.001293915
> java-bitflip:8192 , 0.001149508
> java-bitflip:16384 , 0.001102308
> java-bitflip:32768 , 0.001116782
> 
> java-bitflip:16 , 0.008489137
> java-bitflip:32 , 0.002592102
> java-bitflip:64 , 0.002714038
> java-bitflip:128 , 0.002660729
> java-bitflip:256 , 0.002731328
> java-bitflip:512 , 0.001386984
> java-bitflip:1024 , 0.001290418
> java-bitflip:2048 , 0.001144125
> java-bitflip:4096 , 0.001292783
> java-bitflip:8192 , 0.001423453
> java-bitflip:16384 , 0.001433209
> java-bitflip:32768 , 0.001503469
> 
> java-bitflip:16 , 0.009666127
> java-bitflip:32 , 0.002560116
> java-bitflip:64 , 0.002220535
> java-bitflip:128 , 0.001608121
> java-bitflip:256 , 0.001234845
> java-bitflip:512 , 0.002430928
> java-bitflip:1024 , 0.001766015
> java-bitflip:2048 , 0.001581484
> java-bitflip:4096 , 0.001593586
> java-bitflip:8192 , 0.001952664
> java-bitflip:16384 , 0.001619234
> java-bitflip:32768 , 0.001135541
> 
> java-bitflip:16 , 0.011118166
> java-bitflip:32 , 0.002650564
> java-bitflip:64 , 0.00263125
> java-bitflip:128 , 0.002709398
> java-bitflip:256 , 0.002779049
> java-bitflip:512 , 0.001977314
> java-bitflip:1024 , 0.001177237
> java-bitflip:2048 , 0.001140026
> java-bitflip:4096 , 0.001119551
> java-bitflip:8192 , 0.001119437
> java-bitflip:16384 , 0.001133325
> java-bitflip:32768 , 0.001180998
> 
> java-bitflip:16 , 0.008716385
> java-bitflip:32 , 0.002544727
> java-bitflip:64 , 0.002694378
> java-bitflip:128 , 0.00263498
> java-bitflip:256 , 0.002738082
> java-bitflip:512 , 0.002182567
> java-bitflip:1024 , 0.001165694
> java-bitflip:2048 , 0.001139437
> java-bitflip:4096 , 0.001103763
> java-bitflip:8192 , 0.001098939
> java-bitflip:16384 , 0.00108477
> java-bitflip:32768 , 0.001105667
> 
> java-bitflip:16 , 0.007868587
> java-bitflip:32 , 0.003056887
> java-bitflip:64 , 0.001623479
> java-bitflip:128 , 0.001607546
> java-bitflip:256 , 0.001639512
> java-bitflip:512 , 0.001386188
> java-bitflip:1024 , 0.001190691
> java-bitflip:2048 , 0.001182292
> java-bitflip:4096 , 0.001160852
> java-bitflip:8192 , 0.001216561
> java-bitflip:16384 , 0.001332583
> java-bitflip:32768 , 0.001317823
> 
> java-bitflip:16 , 0.008350494
> java-bitflip:32 , 0.001658587
> java-bitflip:64 , 0.001612241
> java-bitflip:128 , 0.001631172
> java-bitflip:256 , 0.001599996
> java-bitflip:512 , 0.00197649
> java-bitflip:1024 , 0.001307362
> java-bitflip:2048 , 0.001154928
> java-bitflip:4096 , 0.001319034
> java-bitflip:8192 , 0.001147935
> java-bitflip:16384 , 0.00115144
> java-bitflip:32768 , 0.001104784
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-ea-languages/issues/3#issuecomment-154060851
> .

## 

JJ

**Comment by pacastillo** [comment]
Great!

**Comment by gstvrmrlpz** [comment]
Qué unidades de tiempo usas?
Mejor ejecutar todos en la misma máquina..
El 05/11/2015 15:44, "Pedro A. Castillo Valdivieso" notifications@github.com escribió:Great!

**Comment by JJ** [comment]
Sí, ya los ejecuto yo en la mía.

2015-11-05 17:07 GMT+01:00 gustavo notifications@github.com:

> Qué unidades de tiempo usas?
> Mejor ejecutar todos en la misma máquina..
> El 05/11/2015 15:44, "Pedro A. Castillo Valdivieso" <
> notifications@github.com> escribió:Great!
> 
> —Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-ea-languages/issues/3#issuecomment-154104433
> .

## 

JJ

**Comment by vrivas** [comment]
What about javascript or PHP? Do you want for me to try to implement them? Do you think it can be interesting?

**Comment by JJ** [comment]
PHP. If only to find something slower than Perl.

**Comment by JJ** [comment]
I don't know how to run this... Java sucks.

After compiling, it says:

```
java EaLenguajes
Error: no se ha encontrado o cargado la clase principal EaLenguajes
```

**Comment by mariosky** [comment]
Algo de CLASSPATH ?

**Comment by deantares** [comment]
I think it's easy if i upload the jar file. To run it: 

```
java -jar ea-languajes.jar
```

30aac29e4b4ea3afbed4021360dae971adcd45cf

**Comment by JJ** [comment]
I did it already...

2015-11-05 18:51 GMT+01:00 Antonio Fernández Ares notifications@github.com
:

> I think it's easy if i upload the jar file. To run it:
> 
> java -jar ea-languajes.jar
> 
> 26b8780
> https://github.com/geneura-papers/2015-ea-languages/commit/26b87807d548f2bb26e0231dae84246831fe8e0c
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-ea-languages/issues/3#issuecomment-154136485
> .

## 

JJ

**Comment by vrivas** [comment]
PHP-bitflip: 16, 0.038064002990723
PHP-bitflip: 32, 0.039497137069702
PHP-bitflip: 64, 0.042196989059448
PHP-bitflip: 128, 0.0434730052948
PHP-bitflip: 256, 0.043138980865479
PHP-bitflip: 512, 0.039585113525391
PHP-bitflip: 1024, 0.042947053909302
PHP-bitflip: 2048, 0.044080972671509
PHP-bitflip: 4096, 0.040929079055786
PHP-bitflip: 8192, 0.043256998062134
PHP-bitflip: 16384, 0.038151979446411
PHP-bitflip: 32768, 0.041486978530884
