### ISSUE TITLE
Warning!!! Differences in implementations

### ISSUE THREAD

**Issue by vrivas** [geneura-papers/2015-ea-languages#5]
Hi, everyone!
I've been reading the different implementations in the different languages and I think we are using two ways to initialize chromosomes: some of us establish all the bits to 0, while some others do it randomly (50% are 0 and 50% are 1). 
Maybe I'm wrong; so, please, revise and tell me the correct way to do it (I'm implementing in PHP)
Thanks,
Victor

**Comment by JJ** [comment]
2015-11-05 18:02 GMT+01:00 Víctor Manuel Rivas Santos <
notifications@github.com>:

> Hi, everyone!
> I've been reading the different implementations in the different languages
> and I think we are using two ways to initialize chromosomes: some of us
> establish all the bits to 0, while some others do it randomly (50% are 0
> and 50% are 1).
> Maybe I'm wrong; so, please, revise and tell me the correct way to do it
> (I'm implementing in PHP)
> 
> Second one is correct. I'm fixing those that do not do it that way.

JJ

**Comment by vrivas** [comment]
Hi again!! @JJ 
For mutation,  we have maximum length equal to 65536, while for bitflip and xover the maximum length is 32768... I'm pretty sure you'll probably have good reasons to do this, but just wanted to warn.

**Comment by JJ** [comment]
It takes a f*cking long time to xover and maxones for that length. I just took it off.
